//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BH3_QRCodeScanner {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_Json {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Json() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BH3_QRCodeScanner.Resource_Json", typeof(Resource_Json).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;operators&quot;: &quot;1&quot;,
        ///    &quot;merchant_id&quot;: &quot;590&quot;,
        ///    &quot;isRoot&quot;: &quot;0&quot;,
        ///    &quot;domain_switch_count&quot;: &quot;0&quot;,
        ///    &quot;sdk_type&quot;: &quot;1&quot;,
        ///    &quot;sdk_log_type&quot;: &quot;1&quot;,
        ///    &quot;timestamp&quot;: &quot;1613035486182&quot;,
        ///    &quot;support_abis&quot;: &quot;x86,armeabi-v7a,armeabi&quot;,
        ///    &quot;access_key&quot;: &quot;&quot;,
        ///    &quot;sdk_ver&quot;: &quot;3.4.2&quot;,
        ///    &quot;oaid&quot;: &quot;&quot;,
        ///    &quot;dp&quot;: &quot;1440*810&quot;,
        ///    &quot;original_domain&quot;: &quot;&quot;,
        ///    &quot;imei&quot;: &quot;330000000142738&quot;,
        ///    &quot;version&quot;: &quot;1&quot;,
        ///    &quot;udid&quot;: &quot;KREhESMUI0F4T3hPM08zSTEAZ1NhAnIYfA==&quot;,
        ///    &quot;apk_sign&quot;: &quot;d1b01b32b10526be2659108204a751d8&quot;,
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string modolcaptcha_B {
            get {
                return ResourceManager.GetString("modolcaptcha_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;operators&quot;: &quot;1&quot;,
        ///    &quot;merchant_id&quot;: &quot;590&quot;,
        ///    &quot;isRoot&quot;: &quot;0&quot;,
        ///    &quot;domain_switch_count&quot;: &quot;0&quot;,
        ///    &quot;sdk_type&quot;: &quot;1&quot;,
        ///    &quot;sdk_log_type&quot;: &quot;1&quot;,
        ///    &quot;timestamp&quot;: &quot;1631325134377&quot;,
        ///    &quot;support_abis&quot;: &quot;x86,armeabi-v7a,armeabi&quot;,
        ///    &quot;access_key&quot;: &quot;&quot;,
        ///    &quot;sdk_ver&quot;: &quot;3.4.2&quot;,
        ///    &quot;oaid&quot;: &quot;&quot;,
        ///    &quot;dp&quot;: &quot;1440*810&quot;,
        ///    &quot;original_domain&quot;: &quot;&quot;,
        ///    &quot;imei&quot;: &quot;330000000142738&quot;,
        ///    &quot;version&quot;: &quot;1&quot;,
        ///    &quot;udid&quot;: &quot;KREhESMUI0F4T3hPM08zSTEAZ1NhAnIYfA&quot;,
        ///    &quot;apk_sign&quot;: &quot;d1b01b32b10526be2659108204a751d8&quot;,
        ///   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string modollogin_B {
            get {
                return ResourceManager.GetString("modollogin_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;operators&quot;: &quot;1&quot;,
        ///    &quot;merchant_id&quot;: &quot;590&quot;,
        ///    &quot;isRoot&quot;: &quot;0&quot;,
        ///    &quot;domain_switch_count&quot;: &quot;0&quot;,
        ///    &quot;sdk_type&quot;: &quot;1&quot;,
        ///    &quot;sdk_log_type&quot;: &quot;1&quot;,
        ///    &quot;timestamp&quot;: &quot;1631325134181&quot;,
        ///    &quot;support_abis&quot;: &quot;x86,armeabi-v7a,armeabi&quot;,
        ///    &quot;access_key&quot;: &quot;&quot;,
        ///    &quot;sdk_ver&quot;: &quot;3.4.2&quot;,
        ///    &quot;oaid&quot;: &quot;&quot;,
        ///    &quot;dp&quot;: &quot;1440*810&quot;,
        ///    &quot;original_domain&quot;: &quot;&quot;,
        ///    &quot;imei&quot;: &quot;330000000142738&quot;,
        ///    &quot;version&quot;: &quot;1&quot;,
        ///    &quot;udid&quot;: &quot;KREhESMUI0F4T3hPM08zSTEAZ1NhAnIYfA&quot;,
        ///    &quot;apk_sign&quot;: &quot;d1b01b32b10526be2659108204a751d8&quot;,
        ///   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string modolrsa_B {
            get {
                return ResourceManager.GetString("modolrsa_B", resourceCulture);
            }
        }
    }
}
